stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

build:staging:windows32:
  stage: build
  tags:
    - autobuild
    - windows
  before_script:
    - pipenv install
  script:
    - pipenv run autobuild configure -c Release -A32 -- -DFMODSTUDIO=ON -DNVAPI=ON -DUSE_LTO=OFF -DVS_DISABLE_FATAL_WARNINGS=ON -DUSE_CRASHPAD=ON -DCRASHPAD_URL="$env:SENTRY_DSN" -DVIEWER_CHANNEL_BASE:STRING="Alpha" -DPACKAGE=ON
    - pipenv run autobuild build -c Release -A32 --no-configure
    - sentry-cli upload-dif SingularityAlphaViewer.exe singularity-bin.pdb crashpad_handler.exe crashpad_handler.pdb fmod.dll libcrypto-1_1-x64.dll libcrypto-1_1-x64.pdb libssl-1_1-x64.dll libssl-1_1-x64.pdb vcruntime140.dll msvcp140.dll glod.dll
  artifacts:
    paths:
      - build-vc-32/newview/Release/Singularity*Setup.exe
  only:
    refs:
      - master
      
build:staging:windows64:
  stage: build
  tags:
    - autobuild
    - windows
  before_script:
    - pipenv install
  script:
    - pipenv run autobuild configure -c Release -A64 -- -DFMODSTUDIO=ON -DNVAPI=ON -DUSE_LTO=ON -DVS_DISABLE_FATAL_WARNINGS=ON -DUSE_CRASHPAD=ON -DCRASHPAD_URL="$env:SENTRY_DSN" -DVIEWER_CHANNEL_BASE:STRING="Alpha" -DPACKAGE=ON
    - pipenv run autobuild build -c Release -A64 --no-configure
    - sentry-cli upload-dif SingularityAlphaViewer.exe singularity-bin.pdb crashpad_handler.exe crashpad_handler.pdb fmod.dll libcrypto-1_1-x64.dll libcrypto-1_1-x64.pdb libssl-1_1-x64.dll libssl-1_1-x64.pdb libhunspell.dll libhunspell.pdb vcruntime140.dll msvcp140.dll glod.dll
  artifacts:
    paths:
      - build-vc-64/newview/Release/Singularity*Setup.exe
  only:
    refs:
      - master
      
deploy:staging:
  stage: deploy
  tags:
    - autobuild
    - windows
  script:
    - mkdir upload
    - cp build-vc-*/newview/Release/Singularity*Setup.exe upload/
    - $FileNameWin32 = Get-ChildItem -Path . -Name -Include upload/Singularity*_i686_Setup.exe
    - curl.exe -v --user "$env:AUTOBUILD_HTTP_USER:$env:AUTOBUILD_HTTP_PASS" --upload-file ./$FileNameWin32 https://pkg.alchemyviewer.org/repository/singularity-project/alpha/$FileNameWin32
    - $FileNameWin64 = Get-ChildItem -Path . -Name -Include upload/Singularity*_x86_64_Setup.exe
    - curl.exe -v --user "$env:AUTOBUILD_HTTP_USER:$env:AUTOBUILD_HTTP_PASS" --upload-file ./$FileNameWin64 https://pkg.alchemyviewer.org/repository/singularity-project/alpha/$FileNameWin64
  only:
    - master

